### ISSUE TITLE
Nested input

### ISSUE THREAD

**Issue by hrox** [jamesmacaulay/elm-graphql#22]
Hi, I'm trying to use your library with Graph.cool and email authentication. Trying to log in the user, I build the mutation query like this:

```
loginMutation : Document Mutation String LoginVars
loginMutation =
    let
        emailVar =
            Var.required "email" .email Var.string
        
        passwordVar =
            Var.required "password" .password Var.string

    in
        mutationDocument <|
            extract
                (field "signinUser" []
                    (extract (field "email"
                        [ ( "email", Arg.variable emailVar )
                        , ( "password", Arg.variable passwordVar )
                        ]
                        (extract (field "token" [] string))
                    ))
                )
```

The mutation query should have the following structure:
```
mutation {
  signinUser(email: {
    email: "some@email.com"
    password: "somepassword"
  }) {
    token
  }
}
```

Is there a way to achieve this with your library? I've been trying this for quite some hours now.

Regards

**Comment by jamesmacaulay** [comment]
You're treating the `email` argument of the `signinUser` field as if it were its own field to be selected:

https://ellie-app.com/3LNsyCVzq5wa1/2

So the above code results in the following mutation document:

```graphql
mutation ($email: String!, $password: String!) {
  signinUser {
    email(email: $email, password: $password) {
      token
    }
  }
}
```

Instead, all the arguments to the `signinUser` field need to go in the argument list that you currently have empty, using `Arg.object` to describe the value of that top-level `email` argument:

```elm
mutationDocument <|
    extract
        (field "signinUser"
            [ ( "email"
                , Arg.object
                    [ ( "email", Arg.variable emailVar )
                    , ( "password", Arg.variable passwordVar )
                    ]
                )
            ]
            (extract (field "token" [] string))
        )
```

https://ellie-app.com/3LNsyCVzq5wa1/3

Does that help?

**Comment by hrox** [comment]
James, thank you for your quick reply. I tried your suggestion and it works just as expected. I'm looking forward to looking more into what seems like a great library.

Thanks for your work!
