### ISSUE TITLE
[Question] How do I run tests?

### ISSUE THREAD

**Issue by sunwukonga** [jamesmacaulay/elm-graphql#32]
When I run `elm test` from the root directory, it complains that `./tests/Main.elm` doesn't exist.

If I run `elm test tests/Graphql/Request/BuilderTests.elm` I run into the following error:
```
The test run failed because it encountered a runtime exception:

 TypeError: testModule.worker is not a function
    at evalElmCode (/usr/lib/node_modules/elm-test/bin/elm-test:178:24)
    at /usr/lib/node_modules/elm-test/bin/elm-test:303:33
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I can do `elm test init`, which creates a `tests/Main.elm`, but I'm sure this isn't how you've been running tests till this point.

**Comment by jamesmacaulay** [comment]
It looks like you might need to update your `elm-test` to the latest version; at some point I think around 0.18.0 they changed the way it looks for test files. I'll add a note in the README on how to run the tests that includes this important detail.

**Comment by sunwukonga** [comment]
Makes sense, I'm at 0.18.2

**Comment by sunwukonga** [comment]
Fixed. Definitely my problem 👍
