### ISSUE TITLE
Need access to Http.Response on error

### ISSUE THREAD

**Issue by anagrius** [jamesmacaulay/elm-graphql#34]
We use custom fields in our error responses apart from just `message` and `locations`.
These fields contain details about which fields that did not validate, i.e. for form validation.

here is an example:

```json
[{ "message": "Invalid user input", 
    "locations": [],
    "errors": { "name": "The name 'foo' is already taken.", "size": "Size must be greater than zero" }
}]
```

Currently the additional information is stripped out by elm-graphql when it parses the error result.

I see the following solutions:

1. We change our protocol to include the errors in the result data instead of error.
2. You allow access to the Http.Response in `GraphQLError`, so people can do whatever they want with it including additional parsing.
3. You allow passing in an Json Decoder for parsing errors when sending a query/mutation.

**Comment by jamesmacaulay** [comment]
You can access the raw HTTP response with the `...Raw` variants of the send functions:

http://package.elm-lang.org/packages/jamesmacaulay/elm-graphql/1.8.0/GraphQL-Client-Http#customSendQueryRaw

This allows you to decode the success and error data however you like, using the `responseDataDecoder` function to form the core of the success decoder.

**Comment by jamesmacaulay** [comment]
(For 2.0 I'd like to make it easier to extend the deciding process, especially for errors, without having to do it this way...but this works for now.)

**Comment by anagrius** [comment]
Super, thanks. Missed that one. Closing.
