### ISSUE TITLE
Feature request: Multipart/form-data

### ISSUE THREAD

**Issue by tanishi109** [jamesmacaulay/elm-graphql#38]
Do you have the future plan for supporting multipart/form-data?
I would like to use multipart/form-data for uploading files.

Thank you for your great library 🙏

**Comment by jamesmacaulay** [comment]
No current plans for multipart/form-data requests. I did a bit of research and it looks like there's no standard way of supporting this that works across the various GraphQL server implementations. I'm also not sure about the current state of working with file blob data in Elm, which I think would be necessary for this to be of any use. That being said, if you can get that part working then you could probably write your own version of the `GraphQL.Client.Http` module that does what you want to work with the particular server you're targeting. I'll close this issue for now but if the situation changes meaningfully in the future then I'll revisit it. And if you get something working with your own project, please comment here again as I'd be curious to see how it works!
