### ISSUE TITLE
Examples for sendMutation

### ISSUE THREAD

**Issue by gothy** [jamesmacaulay/elm-graphql#4]
I'm new to both GraphQL and elm-graphql so I'm kinda stuck with building a simple mutation request and decoding the response like this 

```
mutation {
  signinUser(email: {email: "somebody@gmail.com", password: "somepassword" }) {
    token
  }
}
```

It'd be great to see an example in the docs or inside the `/examples` folder :)

**Comment by mathieul** [comment]
Here's an example that could help:

```elm
import GraphQL.Request.Builder as B exposing (SelectionSpec, Field)
import GraphQL.Request.Builder.Arg as Arg
import GraphQL.Request.Builder.Variable as Var
import GraphQL.Client.Http as GraphQLClient

storyTask : B.ValueSpec B.NonNull B.ObjectType StoryTask vars
storyTask =
    B.object StoryTask
        |> B.with (B.field "id" [] B.id)
        |> B.with (B.field "label" [] B.string)

deleteTaskQuery : B.Document B.Mutation StoryTask { vars | taskID : String }
deleteTaskQuery =
    let
        taskIDVar =
            Var.required "taskID" .taskID Var.id

        variables =
            [ ( "id", Arg.variable taskIDVar ) ]
    in
        B.field "deleteTask" variables storyTask
            |> B.extract
            |> B.mutationDocument


deleteTaskRequest : Id -> B.Request B.Mutation StoryTask
deleteTaskRequest id =
    deleteTaskQuery
        |> B.request { taskID = id }
```

For reference here's the GraphQL mutation below:

```graphql
    mutation($taskID: ID!) {
      deleteTask(id: $taskID) {
      id
      label
    }
  }
```

**Comment by jamesmacaulay** [comment]
Yeah thanks for bringing this up @gothy, mutations need examples of their own. Basically all you need to know is: they are built up in exactly the same way as queries, except that you wrap up your `ValueSpec` in a call to `mutationDocument` instead of `queryDocument`. Everything else works the same. Your `signInUser` example could be written rather verbosely like this:

```elm

type alias SignInUserMutationRoot =
    { signInUser : SignInUserPayload
    }


type alias SignInUserPayload =
    { token : String
    }


signInUserMutation : Document Mutation SignInUserMutationRoot vars
signInUserMutation =
    let
        args =
            [ ( "email"
              , Arg.object
                    [ ( "email", Arg.string "somebody@gmail.com" )
                    , ( "password", Arg.string "somepassword" )
                    ]
              )
            ]

        responsePayload =
            object SignInUserPayload
                |> with (field "token" [] string)

        mutationRoot =
            object SignInUserMutationRoot
                |> with (field "signInUser" args responsePayload)
    in
        mutationDocument mutationRoot
```

Notice that all the same functions are used to represent the selection sets of the mutation in the same way that you do for queries. The only difference is the `mutationDocument` call at the end.

I made the example verbose to make it more obvious what's going on, but since you only have one field in each level of nesting in the response, you can do a way with the record types and `extract` the token and decode it on its own as a `String`:

```elm
signInUserMutation : Document Mutation String vars
signInUserMutation =
    mutationDocument
        (extract
            (field "signInUser"
                [ ( "email"
                  , Arg.object
                        [ ( "email", Arg.string "somebody@gmail.com" )
                        , ( "password", Arg.string "somepassword" )
                        ]
                  )
                ]
                (extract
                    (field "token" [] string)
                )
            )
        )
```

**Comment by gothy** [comment]
Thank you both @mathieul and @jamesmacaulay 😄

@jamesmacaulay  should I close this or let it hang around as a reminder for you to add some docs? 😄

**Comment by jamesmacaulay** [comment]
You can leave it as a reminder 👍

**Comment by jamesmacaulay** [comment]
Added mutation examples to [tests](https://github.com/jamesmacaulay/elm-graphql/commit/a626a1b7be4488c863b94ecc081005bed3adb0cb), [docs](https://github.com/jamesmacaulay/elm-graphql/commit/e5d7ca327e92614ad9f8b8fea4115fd53985cfae), and [readme](https://github.com/jamesmacaulay/elm-graphql/commit/db7285c8770b40862470e6fe1af059702d7d22fd).
