### ISSUE TITLE
Document how to set request HTTP headers, etc

### ISSUE THREAD

**Issue by lpil** [jamesmacaulay/elm-graphql#6]
Hello!

My graphql API is secured using a token in a header. How might I set this header using `GraphQL.Client.Http`? Alternatively how might I use this library with the regular `Http` module?

Cheers,
Louis

**Comment by jamesmacaulay** [comment]
I see you found the discussion in #5 as well. This module definitely needs more flexibility, but until the functions are there I suggest using your own version of the module modified to suit your needs:

https://github.com/jamesmacaulay/elm-graphql/blob/master/src/GraphQL/Client/Http.elm

The only private thing it relies on right now is the `GraphQL.Response` module, and only for decoding the errors which isn't much to copy over.

**Comment by jamesmacaulay** [comment]
#7 will be included in next release. Thanks for the input!
